"""schema inicial

Revision ID: c77c6a96d280
Revises:
Create Date: 2026-09-17 15:50:54.285517

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c77c6a96d280"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_name", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "status IN ('RUNNING','SUCCESS','FAILED','SKIPPED')",
            name=op.f("ck_job_runs_status_valido"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_job_runs_fim_depois_do_inicio"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    op.create_index(
        "ix_job_runs_job_name_started_at",
        "job_runs",
        ["job_name", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "failed_login_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('ADMIN','OPERATOR','AUDITOR')", name=op.f("ck_users_role_valido")
        ),
        sa.CheckConstraint(
            "failed_login_attempts >= 0", name=op.f("ck_users_tentativas_nao_negativas")
        ),
        sa.CheckConstraint(
            "length(password_hash) >= 20", name=op.f("ck_users_hash_nao_e_texto_puro")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_email", sa.String(length=254), nullable=True),
        sa.Column("actor_role", sa.String(length=40), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('SUCCESS','FAILURE')", name=op.f("ck_audit_logs_desfecho_valido")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_actor_user_id_occurred_at",
        "audit_logs",
        ["actor_user_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_occurred_at",
        "audit_logs",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_resource_type_resource_id",
        "audit_logs",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tax_id", sa.String(length=14), nullable=False),
        sa.Column("legal_name", sa.String(length=180), nullable=False),
        sa.Column("trade_name", sa.String(length=180), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=13), nullable=True),
        sa.Column(
            "status", sa.String(length=40), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE')", name=op.f("ck_clients_status_valido")
        ),
        sa.CheckConstraint("tax_id ~ '^[0-9]+$'", name=op.f("ck_clients_documento_so_digitos")),
        sa.CheckConstraint(
            "length(tax_id) IN (11, 14)", name=op.f("ck_clients_documento_11_ou_14_digitos")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_clients_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("tax_id", name=op.f("uq_clients_tax_id")),
    )
    op.create_index("ix_clients_legal_name", "clients", ["legal_name"], unique=False)
    op.create_index("ix_clients_status", "clients", ["status"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("created_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        "ix_refresh_tokens_ativos",
        "refresh_tokens",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"], unique=False)
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("monthly_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("due_day", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=40), server_default=sa.text("'ACTIVE'"), nullable=False
        ),
        sa.Column("auto_renew", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "renewal_term_months", sa.Integer(), server_default=sa.text("12"), nullable=False
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=300), nullable=True),
        sa.Column("renewed_to_id", sa.UUID(), nullable=True),
        sa.Column("previous_contract_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status <> 'CANCELLED') OR (cancelled_at IS NOT NULL)",
            name=op.f("ck_contracts_cancelado_tem_data"),
        ),
        sa.CheckConstraint(
            "(status <> 'RENEWED') OR (renewed_to_id IS NOT NULL)",
            name=op.f("ck_contracts_renovado_aponta_sucessor"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','EXPIRING','EXPIRED','RENEWED','CANCELLED')",
            name=op.f("ck_contracts_status_valido"),
        ),
        sa.CheckConstraint(
            "due_day BETWEEN 1 AND 31", name=op.f("ck_contracts_dia_vencimento_valido")
        ),
        sa.CheckConstraint(
            "end_date > start_date", name=op.f("ck_contracts_termino_depois_do_inicio")
        ),
        sa.CheckConstraint("monthly_amount > 0", name=op.f("ck_contracts_mensalidade_positiva")),
        sa.CheckConstraint(
            "renewal_term_months BETWEEN 1 AND 120",
            name=op.f("ck_contracts_prazo_renovacao_valido"),
        ),
        sa.CheckConstraint(
            "renewed_to_id IS NULL OR renewed_to_id <> id",
            name=op.f("ck_contracts_sucessor_nao_e_ele"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_contracts_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_contracts_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["previous_contract_id"],
            ["contracts.id"],
            name=op.f("fk_contracts_previous_contract_id_contracts"),
        ),
        sa.ForeignKeyConstraint(
            ["renewed_to_id"], ["contracts.id"], name=op.f("fk_contracts_renewed_to_id_contracts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
        sa.UniqueConstraint("number", name=op.f("uq_contracts_number")),
    )
    op.create_index("ix_contracts_client_id", "contracts", ["client_id"], unique=False)
    op.create_index("ix_contracts_status", "contracts", ["status"], unique=False)
    op.create_index(
        "ix_contracts_vencimento_aberto",
        "contracts",
        ["end_date"],
        unique=False,
        postgresql_where=sa.text("status IN ('ACTIVE','EXPIRING')"),
    )
    op.create_table(
        "contract_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_contract_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_contract_events_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_events")),
    )
    op.create_index(
        "ix_contract_events_contract_id_occurred_at",
        "contract_events",
        ["contract_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "installments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("competence", sa.String(length=7), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status", sa.String(length=40), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status <> 'PAID') OR (paid_at IS NOT NULL)",
            name=op.f("ck_installments_paga_tem_data"),
        ),
        sa.CheckConstraint(
            "competence ~ '^[0-9]{4}-[0-9]{2}$'",
            name=op.f("ck_installments_competencia_formato_aaaa_mm"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','PAID','OVERDUE','CANCELLED')",
            name=op.f("ck_installments_status_valido"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_installments_valor_positivo")),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_installments_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installments")),
        sa.UniqueConstraint(
            "contract_id", "competence", name="uq_installments_contract_id_competence"
        ),
    )
    op.create_index("ix_installments_contract_id", "installments", ["contract_id"], unique=False)
    op.create_index(
        "ix_installments_vencidas",
        "installments",
        ["due_date"],
        unique=False,
        postgresql_where=sa.text("status IN ('PENDING','OVERDUE')"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.String(length=40), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column(
            "status", sa.String(length=40), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("provider_message_id", sa.String(length=120), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status <> 'SENT') OR (sent_at IS NOT NULL)",
            name=op.f("ck_notifications_enviada_tem_data"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','SENT','FAILED','DEAD_LETTER')",
            name=op.f("ck_notifications_status_valido"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_notifications_tentativas_nao_negativas")),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
            name=op.f("fk_notifications_contract_id_contracts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_notifications_dedupe_key")),
    )
    op.create_index(
        "ix_notifications_a_enviar",
        "notifications",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('PENDING','FAILED')"),
    )
    op.create_index("ix_notifications_contract_id", "notifications", ["contract_id"], unique=False)
    op.create_index("ix_notifications_status", "notifications", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_status", table_name="notifications")
    op.drop_index("ix_notifications_contract_id", table_name="notifications")
    op.drop_index(
        "ix_notifications_a_enviar",
        table_name="notifications",
        postgresql_where=sa.text("status IN ('PENDING','FAILED')"),
    )
    op.drop_table("notifications")
    op.drop_index(
        "ix_installments_vencidas",
        table_name="installments",
        postgresql_where=sa.text("status IN ('PENDING','OVERDUE')"),
    )
    op.drop_index("ix_installments_contract_id", table_name="installments")
    op.drop_table("installments")
    op.drop_index("ix_contract_events_contract_id_occurred_at", table_name="contract_events")
    op.drop_table("contract_events")
    op.drop_index(
        "ix_contracts_vencimento_aberto",
        table_name="contracts",
        postgresql_where=sa.text("status IN ('ACTIVE','EXPIRING')"),
    )
    op.drop_index("ix_contracts_status", table_name="contracts")
    op.drop_index("ix_contracts_client_id", table_name="contracts")
    op.drop_table("contracts")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_family_id", table_name="refresh_tokens")
    op.drop_index(
        "ix_refresh_tokens_ativos",
        table_name="refresh_tokens",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("refresh_tokens")
    op.drop_index("ix_clients_status", table_name="clients")
    op.drop_index("ix_clients_legal_name", table_name="clients")
    op.drop_table("clients")
    op.drop_index("ix_audit_logs_resource_type_resource_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_occurred_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_user_id_occurred_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_index("ix_job_runs_job_name_started_at", table_name="job_runs")
    op.drop_table("job_runs")
    # ### end Alembic commands ###
